// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vauvoxywtpzuyaeznaif.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhdXZveHl3dHB6dXlhZXpuYWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1NjU5NDIsImV4cCI6MjA0OTE0MTk0Mn0.BicM3RA_GqV4ZcmC5JQurz6ac36qwKZ9LnVDTUabJZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);